name: cppimport
channels:
  - conda-forge
dependencies:
  - pybind11
  - mako
  - black
  - regex>=2021
  - flake8
  - isort
  - pytest
  - pytest-cov
  - pre-commit
  - filelock
  - boost
  - ipython
  - numpy
  - threadpoolctl
  - nbconvert
  - nbformat
  - ipykernel
  - blas=*=openblas
